select
    pid::text as p_id,
    product_type_id::text as product_type_id,
    name::text as name,
    url::text as url,
    origin::text as origin,
    thickness::text as thickness,
    material::text as material,
    weave::text as weave,
    weave_feature::text as weave_feature,
    color::text as color,
    brand::text as brand,
    "imageName"::text as image_name,
    "imageType"::text as image_type,
    "internalName"::text as internal_name,
    category::text as category,
    min_price::numeric as min_price,
    max_price::numeric as max_price,
    availability::text as availability,
    aggregate::boolean as aggregate,
    clearance::boolean as clearance,
    long_description::text as long_description,
    shopbyroom::text as shop_by_room,
    dw_insert_timestamp::timestamp as dw_insert_timestamp
from {{ ref('rugs_usa_parent') }}