select
    pid::text as p_id,
    variant::text as variant,
    actual_size::text as actual_size,
    weave_feature::text as weave_feature,
    weave_cat::text as weave_cat,
    size_grp::text as size_grp,
    shipping_size::text as shipping_size,
    shape::text as shape,
    weight::numeric as weight,
    price::numeric as price,
    msrp::numeric as msrp,
    stock_level::integer as stock_level,
    depletion_level::integer as depletion_level,
    low_stock::boolean as low_stock,
    estimated_delivery_date::text as estimated_delivery_date,
    this_isd_range::text as this_isd_range,
    status::text as status,
    origin::text as origin,
    new_arrival::boolean as new_arrival,
    "stockMsg"::text as stock_msg,
    "stockEddMsg"::text as stock_edd_msg,
    other_stock_core::integer as other_stock_core,
    other_stock_compass::integer as other_stock_compass,
    dw_insert_timestamp::timestamp as dw_insert_timestamp
from {{ ref('rugs_usa_variant') }}